# /*
# * Copyright (c) 2026-2030 小猫猫. All rights reserved.
# * 
# * LICENSE NOTE:
# * Any redistribution must retain this copyright notice and license disclaimer.
# *
# * by: 小猫猫
# */
#AndroidIDE: enforce UTF-8 & locale for Gradle daemon
#Sun Apr 05 05:50:04 GMT 2026
android.enableAppCompileTimeRClass=true
android.enableResourceOptimizations=false
android.nonTransitiveRClass=true
android.useAndroidX=true
kotlin.code.style=official
kotlin.incremental.native=true
org.gradle.jvmargs=-Xms210M -Xmx3900m -Dfile.encoding\=UTF-8
android.enableLegacyVariantApi=true
android.suppressUnsupportedCompileSdk=37.0
# 编译SDK
COMPILE_SDK=37
# minSdk
MIN_SDK=28
# TargetSdk
TARGET_SDK=37
# 内部版本-降级与升级的关键版本
VERSION_CODE=15
# 外部版本
VERSION_PREFIX=2.2