#Tuesday, June 16, 2026 12:00:00 GMT
android.enableAppCompileTimeRClass=true
android.nonTransitiveRClass=true
android.useAndroidX=true
kotlin.code.style=official
kotlin.incremental.native=true
org.gradle.jvmargs=-Xms230M -Xmx5100m -Dfile.encoding\=UTF-8
android.suppressUnsupportedCompileSdk=37.0

org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# r8 max 4 Code
# android.r8.maxWorkers=4
# AGP 9.x 
# android.r8.optimizedResourceShrinking=false
# android.builtInKotlin=false
# AGP 8.x
# android.enableResourceOptimizations=false
# android.enableLegacyVariantApi=true

BUILDTOOLS_VERSION=37.0.0
NDK_VERSION=29.0.14206865
CMAKE_VERSION=4.3.3
COMPILE_SDK=37
MIN_SDK=28
TARGET_SDK=37
VERSION_CODE=17
VERSION_PREFIX=3.1