#Wednesday, June 17, 2026 12:00:00 GMT
android.enableAppCompileTimeRClass=true
android.nonTransitiveRClass=true
android.useAndroidX=true
kotlin.code.style=official
kotlin.incremental.native=true
org.gradle.jvmargs=-Xms280M -Xmx5500m -Dfile.encoding\=UTF-8 -XX:+UseG1GC
android.suppressUnsupportedCompileSdk=37.0

BUILDTOOLS_VERSION=37.0.0
NDK_VERSION=29.0.14206865
CMAKE_VERSION=4.3.3
COMPILE_SDK=37
MIN_SDK=28
TARGET_SDK=37
VERSION_CODE=18
VERSION_PREFIX=3.2