name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        run: echo "${{ secrets.SIGNING_KEY_BASE64 }}" | base64 --decode > release.jks

      - name: Build Debug and Release
        run: ./gradlew assembleDebug assembleRelease -w --stacktrace 2>&1 | tee build.log
        env:
          RELEASE_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          
      - name: Upload Build Log
        uses: actions/upload-artifact@v7
        with:
          name: build-log
          path: build.log
          archive: false

      - name: Upload Debug APKs
        uses: actions/upload-artifact@v7
        with:
          name: debug-apks
          path: app/build/outputs/apk/debug/*.apk
          archive: true

      - name: Upload Release APKs
        uses: actions/upload-artifact@v7
        with:
          name: release-apks
          path: app/build/outputs/apk/release/*.apk
          archive: true
