# /*
# * Copyright (c) 2026-2030 小猫猫. All rights reserved.
# * 
# * LICENSE NOTE:
# * Any redistribution must retain this copyright notice and license disclaimer.
# *
# * by: 小猫猫
# */
name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  
jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        run: echo "${{ secrets.SIGNING_KEY_BASE64 }}" | base64 --decode > release.jks

      - name: Build Debug and Release
        run: ./gradlew lint assembleDebug assembleRelease -i -w --stacktrace 2>&1 | tee build.log
        env:
          RELEASE_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          
      - name: Upload Build Log
        uses: actions/upload-artifact@v7
        with:
          name: build-log
          path: build.log
          archive: false
          
      - name: Upload Lint Report HTML
        uses: actions/upload-artifact@v7
        with:
          name: lint-reports-html
          path: app/build/reports/lint-results-debug.html
          archive: false
          
      - name: Upload Lint Report
        uses: actions/upload-artifact@v7
        with:
          name: lint-reports
          path: app/build/reports/*
          archive: true
          
      - name: Upload Kotlin Tooling Metadata
        uses: actions/upload-artifact@v7
        with:
          name: kotlin-tooling-metadata
          path: app/build/kotlinToolingMetadata/kotlin-tooling-metadata.json
          archive: false
          
      - name: Upload Builds Report
        uses: actions/upload-artifact@v7
        with:
          name: builds-reports
          path: build/reports/problems/problems-report.html
          archive: false

      - name: Upload Debug APKs
        uses: actions/upload-artifact@v7
        with:
          name: debug-apks
          path: app/build/outputs/apk/debug/*
          archive: true

      - name: Upload Release APKs
        uses: actions/upload-artifact@v7
        with:
          name: release-apks
          path: app/build/outputs/apk/release/*
          archive: true
          
      - name: Upload Native Debug Symbols
        uses: actions/upload-artifact@v7
        with:
          name: native-debug-symbols
          path: app/build/outputs/native-debug-symbols/*
          archive: true
          
      - name: Upload Apks Logs
        uses: actions/upload-artifact@v7
        with:
          name: apks-logs
          path: app/build/outputs/logs/*
          archive: true
         
      - name: Upload Compose Debug APKs
        uses: actions/upload-artifact@v7
        with:
          name: compose-debug-apks
          path: compose/build/outputs/apk/debug/*
          archive: true

      - name: Upload Compose Release APKs
        uses: actions/upload-artifact@v7
        with:
          name: compose-release-apks
          path: compose/build/outputs/apk/release/*
          archive: true